import { Router } from "express";
import { authenticate } from "../../middleware/auth.middleware";
import * as ctrl from "./playlists.controller";
export const playlistsRouter = Router();
playlistsRouter.get("/",                       authenticate, ctrl.getMyPlaylists);
playlistsRouter.post("/",                      authenticate, ctrl.create);
playlistsRouter.get("/:id",                    ctrl.getById);
playlistsRouter.patch("/:id",                  authenticate, ctrl.update);
playlistsRouter.delete("/:id",                 authenticate, ctrl.remove);
playlistsRouter.post("/:id/songs",             authenticate, ctrl.addSong);
playlistsRouter.delete("/:id/songs/:songId",   authenticate, ctrl.removeSong);
playlistsRouter.patch("/:id/songs/reorder",    authenticate, ctrl.reorder);
